### ISSUE TITLE
Support for other platforms 

### ISSUE THREAD

**Issue by udnaan** [Milerius/shiva#124]
I don't see anything related to other platforms such as linux or Mac. Perhaps it would be a good idea to put something in the main readme that only Windows is supported and if and when will the support for other platforms will come.

**Comment by Milerius** [comment]
What ? 

https://shiva.gitbook.io/project/shiva

**Comment by Milerius** [comment]
I'm closing this one, tell me if something still wrong for you ;)

**Comment by udnaan** [comment]
Ah. That was an oversight on my part. Thanks for the pointer.
