### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [Milerius/shiva#127]
I would like to point out that identifiers like “[`__DO_CASE_STR`](https://github.com/Milerius/shiva/blob/c529e18098feacfc953aa960fc0f08242d272012/modules/enums/shiva/enums/enums.hpp#L42 "Update candidate")” and “[`__PAIRIFY_ELEM`](https://github.com/Milerius/shiva/blob/e89f20e07020feda2cf8307c3d825fc909138d9a/modules/input/shiva/input/keyboard.hpp#L117 "Another update candidate")” [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by Milerius** [comment]
should be fixed in #128

Thank's for pointing this out

**Comment by elfring** [comment]
Thanks for your small source code adjustments.

Were any [update candidates left over](https://github.com/Milerius/shiva/blob/9bc3c02d92511872a035cdce3d1d90d66c45bfe1/modules/pp/shiva/pp/details/pp_for_each.hpp#L8 "Update candidates")?
